name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master
      - homework_5

jobs:
  analyze:
    name: Run analyzer and formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTIONS}}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          cache: true
      - run: |
          echo "${{ secrets.ENV }}" > .env
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format lib/firebase_options.dart # unknown error for generated file
      - run: dart format --set-exit-if-changed .
  build_ios:
    name: Build app (IOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decode firebase_app_id_file.json
        env:
          FIREBASE_APP_ID_FILE_JSON: ${{ secrets.FIREBASE_APP_ID_FILE_JSON }}
        run: echo "$FIREBASE_APP_ID_FILE_JSON" > ios/firebase_app_id_file.json
      - name: Decode GoogleService-Info.plist
        env:
          GOOGLESERVICE_INFO_PLIST: ${{ secrets.GOOGLESERVICE_INFO_PLIST }}
        run: echo "$GOOGLESERVICE_INFO_PLIST" > ios/Runner/GoogleService-Info.plist
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTIONS}}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
      - run: |
          echo "${{ secrets.ENV }}" > .env
      - run: flutter build ios --no-codesign
  build_android:
    name: Build app (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTIONS}}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.5'
          cache: true
      - run: |
          echo "${{ secrets.ENV }}" > .env
      - run: flutter build apk --flavor dev
  build:
    name: Distribution to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTIONS}}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.5'
          cache: true
      - run: |
          echo "${{ secrets.ENV }}" > .env
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --flavor prod
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/prod/release/app-prod-release.apk
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APPID_ANDROID}}
          token: ${{secrets.TOKEN}}
          groups: testers
          file: build/app/outputs/apk/prod/release/app-prod-release.apk
