name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - homework_4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          chanel: 'stable'
      - run: flutter build apk
  analyze:
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .
